import "./globals.css";
import { Caladea } from "next/font/google";

const caladea = Caladea({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={caladea.className} >
      <main className="h-screen bg-[#184e77] flex items-center justify-center">
        <div className="m-auto max-w-screen-md px-4 flex-1 max-h-96 h-full min-h-[420px]">
        <div className="rounded-3xl bg-[#edf6f9] shadow-2xl p-10 h-full w-full">
        {children}
        </div>
        </div>
      </main>
      </body>
    </html>
  );
}
